package com.xcoders.util;

import com.xcoders.DBConnection;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Exports the latest application data into src/main/resources/data.sql.
 *
 * The generated file contains DELETE + INSERT statements so it can be used
 * as a data snapshot for demo, migration, or reset purposes.
 */
public final class DataSqlExporter {

    private static final Path OUTPUT_FILE = Paths.get(
            System.getProperty("user.dir"),
            "src", "main", "resources", "data.sql"
    );

    private static final List<String> DELETE_ORDER = List.of(
            "hotel_images",
            "rooms",
            "hotels",
            "users"
    );

    private static final List<String> INSERT_ORDER = List.of(
            "users",
            "hotels",
            "rooms",
            "hotel_images"
    );

    private DataSqlExporter() {
    }

    /**
     * Writes a full SQL snapshot of persisted records.
     *
     * This method is safe to call after any successful write operation.
     */
    public static synchronized void exportSnapshot() {
        try {
            Files.createDirectories(OUTPUT_FILE.getParent());

            Connection conn = DBConnection.getConnection();
            try (BufferedWriter writer = Files.newBufferedWriter(
                    OUTPUT_FILE,
                    StandardCharsets.UTF_8
            )) {
                writeHeader(writer, conn);
                writer.write("SET FOREIGN_KEY_CHECKS = 0;\n");
                writer.write("\n");

                for (String table : DELETE_ORDER) {
                    writer.write("DELETE FROM " + table + ";\n");
                }

                writer.write("\n");

                for (String table : INSERT_ORDER) {
                    exportTable(conn, writer, table);
                }

                writer.write("SET FOREIGN_KEY_CHECKS = 1;\n");
            }
        } catch (SQLException | IOException e) {
            System.err.println("[DataSqlExporter] Failed to write data.sql: " + e.getMessage());
        }
    }

    private static void writeHeader(BufferedWriter writer, Connection conn) throws IOException, SQLException {
        String dbName = conn.getCatalog() != null ? conn.getCatalog() : "hotel_booking_system";

        writer.write("-- ZenLodges data snapshot\n");
        writer.write("-- Auto-generated by DataSqlExporter\n");
        writer.write("-- Generated at: " + LocalDateTime.now() + "\n\n");
        writer.write("USE " + dbName + ";\n\n");
    }

    private static void exportTable(Connection conn, BufferedWriter writer, String table) throws SQLException, IOException {
        String query = "SELECT * FROM " + table + " ORDER BY 1";

        try (Statement statement = conn.createStatement();
             ResultSet rs = statement.executeQuery(query)) {

            ResultSetMetaData meta = rs.getMetaData();
            int columnCount = meta.getColumnCount();

            boolean wroteAnyRows = false;
            while (rs.next()) {
                wroteAnyRows = true;
                writer.write("INSERT INTO " + table + " (");

                for (int i = 1; i <= columnCount; i++) {
                    if (i > 1) {
                        writer.write(", ");
                    }
                    writer.write(meta.getColumnName(i));
                }

                writer.write(") VALUES (");

                for (int i = 1; i <= columnCount; i++) {
                    if (i > 1) {
                        writer.write(", ");
                    }

                    Object value = rs.getObject(i);
                    int type = meta.getColumnType(i);
                    writer.write(toSqlLiteral(value, type));
                }

                writer.write(");\n");
            }

            if (wroteAnyRows) {
                writer.write("\n");
            }
        }
    }

    private static String toSqlLiteral(Object value, int sqlType) {
        if (value == null) {
            return "NULL";
        }

        switch (sqlType) {
            case Types.BIT:
            case Types.BOOLEAN:
                return Boolean.TRUE.equals(value) ? "1" : "0";

            case Types.TINYINT:
            case Types.SMALLINT:
            case Types.INTEGER:
            case Types.BIGINT:
            case Types.REAL:
            case Types.FLOAT:
            case Types.DOUBLE:
            case Types.NUMERIC:
            case Types.DECIMAL:
                return String.valueOf(value);

            case Types.DATE:
            case Types.TIME:
            case Types.TIMESTAMP:
                return "'" + escapeSql(String.valueOf(value)) + "'";

            case Types.BINARY:
            case Types.VARBINARY:
            case Types.LONGVARBINARY:
                return toHexLiteral((byte[]) value);

            default:
                return "'" + escapeSql(String.valueOf(value)) + "'";
        }
    }

    private static String toHexLiteral(byte[] bytes) {
        if (bytes == null || bytes.length == 0) {
            return "X''";
        }

        StringBuilder hex = new StringBuilder(bytes.length * 2);
        for (byte b : bytes) {
            hex.append(String.format("%02X", b));
        }
        return "X'" + hex + "'";
    }

    private static String escapeSql(String value) {
        return value
                .replace("\\", "\\\\")
                .replace("'", "''")
                .replace("\r", "\\r")
                .replace("\n", "\\n")
                .replace("\t", "\\t");
    }
}
