-- ZenLodges data snapshot
-- Auto-generated by DataSqlExporter
-- Generated at: 2026-04-18T14:49:12.196468700

USE hotel_booking_system;

SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM hotel_images;
DELETE FROM rooms;
DELETE FROM hotels;
DELETE FROM users;

INSERT INTO users (user_id, name, email, password, role, status, created_at) VALUES (1, 'Platform Admin', 'admin@zenlodges.com', 'admin123', 'PLATFORM_ADMIN', 'ACTIVE', '2026-03-19 14:59:51.0');
INSERT INTO users (user_id, name, email, password, role, status, created_at) VALUES (5, 'Hotel1 Admin', 'hotel1admin@zenlodges.com', 'hotel1admin123', 'HOTEL_ADMIN', 'ACTIVE', '2026-03-20 03:52:12.0');
INSERT INTO users (user_id, name, email, password, role, status, created_at) VALUES (6, 'Hotel2 Admin', 'hotel2admin@zenlodges.com', 'hotel2admin123', 'HOTEL_ADMIN', 'ACTIVE', '2026-03-22 13:49:58.0');
INSERT INTO users (user_id, name, email, password, role, status, created_at) VALUES (7, 'User1', 'user1@gmail.com', 'user1123', 'GUEST', 'ACTIVE', '2026-03-23 01:46:53.0');

INSERT INTO hotels (hotel_id, name, location, type, description, status, hotel_admin_id, approved_by, created_at, approved_at) VALUES (2, 'Corporate Stays Downtown', 'San Francisco, California', 'Business', 'Modern business hotel with meeting rooms, conference facilities, high-speed internet, and 24-hour business center for corporate travelers.', 'APPROVED', 5, 1, '2026-03-20 03:52:12.0', '2026-03-20 03:53:38.0');
INSERT INTO hotels (hotel_id, name, location, type, description, status, hotel_admin_id, approved_by, created_at, approved_at) VALUES (3, 'Village Mehfil', 'Islamabad, Pakistan', 'Luxury', 'NIce in the vacinity.', 'APPROVED', 6, 1, '2026-03-22 13:49:59.0', '2026-04-18 16:19:10.0');

INSERT INTO rooms (room_id, hotel_id, room_number, type, price, status, created_at) VALUES (1, 2, '1', 'Deluxe', 30000.00, 'AVAILABLE', '2026-04-18 19:30:18.0');

INSERT INTO hotel_images (image_id, hotel_id, image_path, image_type, is_primary, uploaded_at) VALUES (1, 2, 'hotel-images/hotel_2_main_996f6b9d.jpg', 'MAIN', 1, '2026-03-20 03:52:13.0');
INSERT INTO hotel_images (image_id, hotel_id, image_path, image_type, is_primary, uploaded_at) VALUES (2, 2, 'hotel-images/hotel_2_reference_d0fa8f9d.jpg', 'REFERENCE', 0, '2026-03-20 03:52:13.0');
INSERT INTO hotel_images (image_id, hotel_id, image_path, image_type, is_primary, uploaded_at) VALUES (3, 2, 'hotel-images/hotel_2_reference_95b9c7de.jpg', 'REFERENCE', 0, '2026-03-20 03:52:13.0');
INSERT INTO hotel_images (image_id, hotel_id, image_path, image_type, is_primary, uploaded_at) VALUES (4, 3, 'hotel-images/hotel_3_main_a9b83478.jpg', 'MAIN', 1, '2026-03-22 13:49:59.0');

SET FOREIGN_KEY_CHECKS = 1;
