-- ZenLodges data snapshot
-- Auto-generated by DataSqlExporter
-- Generated at: 2026-03-22T19:16:01.251921200

USE hotel_booking_system;

SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM hotel_images;
DELETE FROM rooms;
DELETE FROM hotels;
DELETE FROM users;

INSERT INTO users (user_id, name, email, password, role, status, created_at) VALUES (1, 'Admin', 'admin@zenlodges.com', 'admin123', 'ADMIN', 'ACTIVE', '2026-03-19 04:55:35.0');
INSERT INTO users (user_id, name, email, password, role, status, created_at) VALUES (2, 'Test User', 'copilot_test_1773878452@mail.com', 'abc123', 'GUEST', 'ACTIVE', '2026-03-19 05:00:52.0');
INSERT INTO users (user_id, name, email, password, role, status, created_at) VALUES (3, 'Probe', 'register_probe_1773860496@mail.com', 'p', 'GUEST', 'ACTIVE', '2026-03-19 05:01:36.0');
INSERT INTO users (user_id, name, email, password, role, status, created_at) VALUES (4, 'a', 'a', 'a', 'GUEST', 'ACTIVE', '2026-03-19 05:04:49.0');
INSERT INTO users (user_id, name, email, password, role, status, created_at) VALUES (5, 'Mr. Engg', 'E@mess.com', 'enggmess', 'HOTEL_ADMIN', 'ACTIVE', '2026-03-21 23:13:52.0');
INSERT INTO users (user_id, name, email, password, role, status, created_at) VALUES (6, 'Ali', 'A@com', 'A', 'GUEST', 'ACTIVE', '2026-03-21 23:39:50.0');
INSERT INTO users (user_id, name, email, password, role, status, created_at) VALUES (7, 'hadmin', 'h@admin.com', 'hadmin', 'HOTEL_ADMIN', 'ACTIVE', '2026-03-21 23:44:52.0');
INSERT INTO users (user_id, name, email, password, role, status, created_at) VALUES (8, 'admin', 'admin', 'admin', 'GUEST', 'ACTIVE', '2026-03-22 03:16:44.0');
INSERT INTO users (user_id, name, email, password, role, status, created_at) VALUES (9, 'pltad', 'pltad@com', 'plt123', 'PLATFORM_ADMIN', 'ACTIVE', '2026-03-22 03:24:08.0');
INSERT INTO users (user_id, name, email, password, role, status, created_at) VALUES (10, 'lmp', 'lm@com', 'lmnopq', 'HOTEL_ADMIN', 'ACTIVE', '2026-03-22 18:40:07.0');
INSERT INTO users (user_id, name, email, password, role, status, created_at) VALUES (11, 'lmp', 'lmnop@com', 'lmnopq', 'HOTEL_ADMIN', 'ACTIVE', '2026-03-22 18:40:19.0');
INSERT INTO users (user_id, name, email, password, role, status, created_at) VALUES (12, 'asdf', 'asdf@com', 'asdfgh', 'HOTEL_ADMIN', 'ACTIVE', '2026-03-22 18:47:19.0');
INSERT INTO users (user_id, name, email, password, role, status, created_at) VALUES (14, 'qwerty', 'qwe@com', 'qwerty', 'HOTEL_ADMIN', 'ACTIVE', '2026-03-22 18:51:48.0');
INSERT INTO users (user_id, name, email, password, role, status, created_at) VALUES (15, 'asdc', 'asdc', 'asdcvb', 'GUEST', 'ACTIVE', '2026-03-22 22:53:03.0');

INSERT INTO hotels (hotel_id, name, location, type, description, status, hotel_admin_id, approved_by, created_at, approved_at) VALUES (2, 'lagoon', 'ISB', 'Resort', '', 'APPROVED', 14, 9, '2026-03-22 18:51:48.0', '2026-03-22 18:53:32.0');

INSERT INTO rooms (room_id, hotel_id, room_number, type, price, status, created_at) VALUES (1, NULL, '1', 'Single', 11111.00, 'AVAILABLE', '2026-03-19 04:56:47.0');
INSERT INTO rooms (room_id, hotel_id, room_number, type, price, status, created_at) VALUES (2, NULL, '2', 'Double', 22222.00, 'MAINTENANCE', '2026-03-19 04:57:01.0');
INSERT INTO rooms (room_id, hotel_id, room_number, type, price, status, created_at) VALUES (3, NULL, '3', 'Suite', 333333.00, 'AVAILABLE', '2026-03-19 05:05:15.0');
INSERT INTO rooms (room_id, hotel_id, room_number, type, price, status, created_at) VALUES (4, NULL, '111', 'Double', 12324.00, 'AVAILABLE', '2026-03-22 18:54:11.0');
INSERT INTO rooms (room_id, hotel_id, room_number, type, price, status, created_at) VALUES (6, 2, '123', 'Deluxe', 12345.00, 'MAINTENANCE', '2026-03-22 21:13:51.0');
INSERT INTO rooms (room_id, hotel_id, room_number, type, price, status, created_at) VALUES (7, 2, '098', 'Single', 1234567.00, 'AVAILABLE', '2026-03-22 21:20:34.0');
INSERT INTO rooms (room_id, hotel_id, room_number, type, price, status, created_at) VALUES (8, 2, '876', 'Deluxe', 987654.00, 'AVAILABLE', '2026-03-22 21:23:37.0');
INSERT INTO rooms (room_id, hotel_id, room_number, type, price, status, created_at) VALUES (9, 2, '12334', 'Suite', 2000000.00, 'AVAILABLE', '2026-03-22 23:12:33.0');

INSERT INTO hotel_images (image_id, hotel_id, image_path, image_type, is_primary, uploaded_at) VALUES (2, 2, 'hotel-images/hotel_2_main_8fe9cba7.png', 'MAIN', 1, '2026-03-22 18:51:49.0');

SET FOREIGN_KEY_CHECKS = 1;
