# Local database configuration for hotel booking system
db.host=localhost
db.port=3306
db.name=hotel_booking_system
db.user=root
db.password= root
# db.password mei apna apna passowrd daal dena mysqlserver ka
